imagetag: test
s3:
  bucket: data.elo7.com.br
  basepath: /configuration/nginx
downloadpath: download-$ENVIRONMENT/
files:
  - s3path: nginx.conf.$ENVIRONMENT
    filename: test.file
commands:
  - mkdir download-$ENVIRONMENT
  - ls -la
  - date
  - uptime